# Air + templ
# https://adrianhesketh.com/2021/05/28/templ-hot-reload-with-air/

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./bin/example"
  cmd = "go build -o bin ./..."
  delay = 1000
  exclude_dir = [
    "bin"
  ]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "pkg"]
  include_ext = ["go", "tpl", "tmpl", "html", "templ" ]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
